name: GitHub Build Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:    
      - main
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
jobs:
  Build-And-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

