name: GitHub Deploy Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    tags:    
      - 'v*'
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}  # The tag that triggered the workflow
          name: Release ${{ github.ref }}
          files: target/*.jar  # Adjust if your JAR is in a different location
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
